### ISSUE TITLE
Multiple calls to 'et get' overwrites existing code.

### ISSUE THREAD

**Issue by radavis** [LaunchAcademy/extraterrestrial#7]
If the submission folder exists, 'et get' should not overwrite existing files.

**Comment by radavis** [comment]
Was this fixed, or is this considered something that will not be fixed?

**Comment by CassandraNewell** [comment]
hi @radavis ! I closed this out because we're deprecating the Ruby version of extraterrestrial after this cohort (replacing it with a [Node version](https://github.com/LaunchAcademy/extraterrestrial-node)), so I wanted to clean up Issues a bit to focus on anything that _needs_ fixing after our most recent release, rather than nice-to-haves. That being said, if you want to submit a fix, go for it! 😁

**Comment by radavis** [comment]
Thanks for the clarification, @CassandraNewell. I created this ticket because it was possible to `et get` an assignment, work on it, then `et get` the same assignment, and then lose your work. This happened to students at least a handful of times while I was working at Launch, and can be a very painful mistake to make, depending on how much effort has been put in between calls to `et get`.

Unfortunately, I don't have the free time to contribute. I was just curious if this was a 'fixed' or 'wont-fix' issue. Sounds like the latter.
